version: '3'

services:

  database:
    image: postgres:latest
    container_name: banking_db
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test:  pg_isready -U postgres -d banking
      interval: 1s
      timeout: 500ms
      retries: 3
    restart: unless-stopped

  app:
    build: ./
    container_name: banking_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 193027
    volumes:
      - ./target:/app/target
    depends_on:
      - database

volumes:
  database-data:
